Main/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('social/', include('social.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from .views import PostModelListView, PostModelDetailView, \
    PostModelUpdateView, PostModelDeleteView, CommentModelDeleteView, UserProfileModelView, ProfileModelUpdateView, \
    AddFollower, RemoveFollower, PostAddLike, PostAddDislike, UserSearch, ListFollowers, CommentAddLike, \
    CommentAddDislike, CommentReplyView, PostNotification, FollowNotification, RemoveNotification, CreateThread, \
    ListThreads, ThreadView, CreateMessage

app_name = 'social'

urlpatterns = [
    path('', PostModelListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostModelDetailView.as_view(), name='post-detail'),
    path('post/update/<int:pk>/', PostModelUpdateView.as_view(), name='post-update'),
    path('post/delete/<int:pk>/', PostModelDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentModelDeleteView.as_view(), name='comment-delete'),

    path('profile/<int:pk>/', UserProfileModelView.as_view(), name='user-profile'),
    path('profile/update/<int:pk>/', ProfileModelUpdateView.as_view(), name='update-profile'),

    path('profile/<int:pk>/followers/add/', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove/', RemoveFollower.as_view(), name='remove-follower'),

    path('post/<int:pk>/like/', PostAddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike/', PostAddDislike.as_view(), name='dislike'),

    path('post/<int:post>/comment/<int:pk>/like/', CommentAddLike.as_view(), name='comment-like'),
    path('post/<int:post>/comment/<int:pk>/dislike/', CommentAddDislike.as_view(), name='comment-dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/reply/', CommentReplyView.as_view(), name='comment-reply'),

    path('search/', UserSearch.as_view(), name='profile-search'),

    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),

    path('notification/<int:notification_pk>/post/<int:post_pk>/', PostNotification.as_view(),
         name='post-notification'),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>/', FollowNotification.as_view(),
         name='follow-notification'),

    path('notification/delete/<int:notification_pk>/', RemoveNotification.as_view(), name='notification-delete'),

    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),

    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),


]

social/forms.py
from django import forms
from .models import PostModel, CommentModel


class PostModelForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Write something'
        })
    )
    image = forms.ImageField(required=False)

    class Meta:
        model = PostModel
        fields = ['body', 'image']


class CommentModelForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
        })
    )

    class Meta:
        model = CommentModel
        fields = ['comment']


class ThreadForm(forms.Form):
    username = forms.CharField(label='', max_length=100)


class MessageForm(forms.Form):
    message = forms.CharField(label='', max_length=100)





social/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views import View
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .forms import PostModelForm, CommentModelForm, ThreadForm, MessageForm
from .models import PostModel, CommentModel, UserProfileModel, NotificationModel, ThreadModel, MessageModel
from django.views.generic.edit import UpdateView, DeleteView


class PostModelListView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        logged_in_user = request.user
        posts = PostModel.objects.filter(
            author__profile__followers__in=[logged_in_user.id]
        ).order_by('-created_at')
        form = PostModelForm()
        context = {
            'post_list': posts,
            'form': form,

        }
        return render(request, 'social/post_list.html', context)

    def post(self, request, *args, **kwargs):
        logged_in_user = request.user
        posts = PostModel.objects.filter(
            author__profile__followers__in=[logged_in_user.id]
        ).order_by('-created_at')
        form = PostModelForm(request.POST, files=request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()

        context = {
            'post_list': posts,
            'form': form,

        }
        return render(request, 'social/post_list.html', context)


class PostModelDetailView(LoginRequiredMixin, View):

    def get(self, request, pk, *args, **kwargs):
        post = PostModel.objects.get(pk=pk)
        form = CommentModelForm()
        comments = CommentModel.objects.filter(post=post).order_by('-created_at')

        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }

        return render(request, 'social/post_detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        post = PostModel.objects.get(pk=pk)
        form = CommentModelForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

        comments = CommentModel.objects.filter(post=post).order_by('-created_at')

        notification = NotificationModel.objects.create(
            notification_type=2, from_user=request.user,
            to_user=post.author, post=post
        )

        context = {
            'post': post,
            'form': form,
            'comments': comments,

        }

        return render(request, 'social/post_detail.html', context)


class PostModelUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = PostModel
    fields = ['body']
    template_name = 'social/post_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('social:post-detail', kwargs={'pk': pk})

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class PostModelDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = PostModel
    template_name = 'social/post_delete.html'
    success_url = reverse_lazy('social:post-list')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class CommentModelDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CommentModel
    template_name = 'social/comment_delete.html'

    # success_url = reverse_lazy('social:post-detail')

    def get_success_url(self):
        pk = self.kwargs['post_pk']
        return reverse_lazy('social:post-detail', kwargs={'pk': pk})

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author


class UserProfileModelView(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfileModel.objects.get(pk=pk)
        user = profile.user
        posts = PostModel.objects.filter(author=user).order_by('-created_at')

        # Start adding followers
        followers = profile.followers.all()

        if len(followers) == 0:
            is_following = False

        for follower in followers:
            if follower == request.user:
                is_following = True
                break
            else:
                is_following = False

        number_of_followers = len(followers)
        # End adding followers

        context = {
            'user': user,
            'profile': profile,
            'posts': posts,
            'number_of_followers': number_of_followers,
            'is_following': is_following,
        }

        return render(request, 'social/profile.html', context)


class ProfileModelUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UserProfileModel
    fields = ['name', 'bio', 'birth_date', 'location', 'picture']
    template_name = 'social/profile_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('social:user-profile', kwargs={'pk': pk})

    def test_func(self):
        profile = self.get_object()
        return self.request.user == profile.user


class AddFollower(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfileModel.objects.get(pk=pk)
        profile.followers.add(request.user)

        notification = NotificationModel.objects.create(
            notification_type=3, from_user=request.user,
            to_user=profile.user
        )

        return redirect('social:user-profile', pk=profile.pk)


class RemoveFollower(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfileModel.objects.get(pk=pk)
        profile.followers.remove(request.user)

        return redirect('social:user-profile', pk=profile.pk)


class PostAddLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = PostModel.objects.get(pk=pk)

        is_dislike = False
        for dislike in post.dislike.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislike.remove(request.user)

        is_like = False
        for like in post.like.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.like.add(request.user)
            notification = NotificationModel.objects.create(
                notification_type=3, from_user=request.user,
                to_user=post.author, post=post
            )

        if is_like:
            post.like.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class PostAddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = PostModel.objects.get(pk=pk)

        is_like = False
        for like in post.like.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.like.remove(request.user)

        is_dislike = False
        for dislike in post.dislike.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislike.add(request.user)

        if is_dislike:
            post.dislike.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class UserSearch(View):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('query')
        profile_list = UserProfileModel.objects.filter(
            Q(user__username__icontains=query)
        )

        context = {
            'profile_list': profile_list,
        }
        return render(request, 'social/search.html', context)


class ListFollowers(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfileModel.objects.get(pk=pk)
        followers = profile.followers.all()

        context = {
            'profile': profile,
            'followers': followers
        }
        return render(request, 'social/followers_list.html', context)


class CommentAddLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        comment = CommentModel.objects.get(pk=pk)

        is_dislike = False
        for dislike in comment.dislike.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            comment.dislike.remove(request.user)

        is_like = False
        for like in comment.like.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            comment.like.add(request.user)
            notification = NotificationModel.objects.create(
                notification_type=1, from_user=request.user,
                to_user=comment.author, comment=comment
            )

        if is_like:
            comment.like.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class CommentAddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        comment = CommentModel.objects.get(pk=pk)

        is_like = False
        for like in comment.like.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            comment.like.remove(request.user)

        is_dislike = False
        for dislike in comment.dislike.all():
            if dislike == request.user:
                is_dislike = True

templates/social/comment_delete.html
{% extends 'layouts/base.html' %}


{% block content %}
    <div class="container">

        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'social:post-detail' object.pk %}" class="btn btn-light font-weight-bolder">Back To Post</a>
            </div>
        </div>

        <div class="row justify-content-center mt-3 mb-5">
            <div class="col-md-5 col-sm-12 border-bottom">
                <form method="POST">
                    {% csrf_token %}
                    <h5>Are You Sure?</h5>
                    <p>You are about to delete this comment, this cannot be undone.</p>
                    <button type="submit" class="btn-block btn btn-danger">Yes</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/social/create_thread.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12 p-5">
                <a href="{% url 'social:inbox' %}" class="btn btn-light">Back to your inbox</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 p-5">
                <h3>Start a Conversation</h3>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
    <div class="col-md-5 col-sm-12">
        <form method="POST" action="">
            {% csrf_token %}
            <p>Enter the username for the person you would talk to.</p>
            {{ form.as_table }}
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-success mt-3">Continue</button>

            </div>
        </form>

    </div>

    </div>


{% endblock %}





templates/social/inbox.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12 p-5">
                <h3>Your Conversations</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 p-5">
                <form method="get" action="{% url 'social:create-thread' %}">
                    <button class="btn btn-light p-3">Start a Conversation</button>
                </form>
            </div>
        </div>

        {% for thread in threads.all %}

            <div class="row mb-3">
                <div class="card col-md-12 p-5 shadow-sm">
                    <h5>{{ thread.user }} - {{ thread.receiver }}</h5>
                    <a class="stretched-link" href="{% url 'social:thread' thread.pk %}"></a>
                </div>
            </div>

        {% endfor %}

    </div>

{% endblock content %}

templates/social/post_detail.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <div class="container">

        <div class="row mt-5">
            <div class="col-md-5 col-sm-6">
                <a href="{% url 'social:post-list' %}" class="btn btn-light font-weight-bolder">Back To Feed</a>
            </div>
        </div>

        <div class="row justify-content-center mt-3 mb-5">
            <div class="col-md-5 col-sm-12 border-bottom">


                <div class="mt-3">
                    <a href="{% url 'social:user-profile' post.author.profile.pk %}">
                        <img class="rounded-circle post-img float-left mr-2" height="30" width="30"
                             src="{{ post.author.profile.picture.url }}" alt="">
                    </a>
                    <p class=""><a href="{% url 'social:user-profile' post.author.profile.pk %}"
                                   style="text-decoration: none"
                                   class="text-primary">@{{ post.author }}</a> {{ post.created_at }}
                    </p>
                </div>


                {% if request.user == post.author %}
                    <a href="{% url 'social:post-update' post.pk %}"><i class="fa fa-edit"></i></a>
                    <a href="{% url 'social:post-delete' post.pk %}"><i class="fa fa-trash"></i></a>
                {% endif %}

                <p>{{ post.body }}</p>

                <div class="d-flex flex-row">
                    <form method="post" action="{% url 'social:like' post.pk %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <button type="submit" style="background-color: transparent; border: none; box-shadow: none">
                            <i class="far fa-thumbs-up"> <span>{{ post.like.all.count }}</span> </i>
                        </button>
                    </form>

                    <form method="post" action="{% url 'social:dislike' post.pk %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <button type="submit" style="background-color: transparent; border: none; box-shadow: none">
                            <i class="far fa-thumbs-down"> <span>{{ post.dislike.all.count }}</span> </i>
                        </button>
                    </form>
                </div>
            </div>
        </div>

        <div class="row justify-content-center mt-3 mb-5">
            <div class="col-md-5 col-sm-12 border-bottom">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success float-right">Save</button>
                </form>
            </div>
        </div>

        {% for comment in comments %}

            {% if comment.is_parent %}

                <div class="row justify-content-center mt-3 mb-5">
                    <div class="col-md-5 col-sm-12 border-bottom">
                        <p>
                        <div>
                            <a href="{% url 'social:user-profile' comment.author.profile.pk %}">
                                <img class="rounded-circle post-img" height="30" width="30"
                                     src="{{ comment.author.profile.picture.url }}" alt="">
                            </a>
                            <p class="post-text">
                                <a href="{% url 'social:user-profile' comment.author.profile.pk %}">
                                    @{{ comment.author }}</a> {{ comment.created_at }}
                            </p>
                        </div>

                        {% if request.user == comment.author %}
                            <a href="{% url 'social:comment-delete' post.pk comment.pk %}"><i
                                    class="fa fa-trash"></i></a>
                        {% endif %}
                        </p>
                        <p>{{ comment.comment }}</p>

                        <div class="d-flex flex-row">
                            <form method="post" action="{% url 'social:comment-like' post.pk comment.pk %}">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <button type="submit"
                                        style="background-color: transparent; border: none; box-shadow: none">
                                    <i class="far fa-thumbs-up"> <span>{{ comment.like.all.count }}</span> </i>
                                </button>
                            </form>

                            <form method="post" action="{% url 'social:comment-dislike' post.pk comment.pk %}">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <button type="submit"
                                        style="background-color: transparent; border: none; box-shadow: none">
                                    <i class="far fa-thumbs-down"> <span>{{ comment.dislike.all.count }}</span> </i>
                                </button>
                            </form>
                            <div>
                                <button class="remove-default-btn"
                                        style="background-color: transparent; border: none; box-shadow: none">
                                    <i class="far fa-comment-dots" onclick="commentReplyToggle('{{ comment.pk }}')"></i>
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="row justify-content-center mt-3 mb-5 d-none" id="{{ comment.pk }}">
                    <div class="col-md-5 col-sm-12 border-bottom">
                        <form method="post" action="{% url 'social:comment-reply' post.pk comment.pk %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success float-right">Save</button>
                        </form>
                    </div>
                </div>

                {% for child_comment in comment.children %}
                    <div class="row justify-content-center mt-3 mb-5 ml-5">
                        <div class="col-md-5 col-sm-12 border-bottom">
                            <p>
                            <div>
                                <a href="{% url 'social:user-profile' child_comment.author.profile.pk %}">
                                    <img class="rounded-circle post-img" height="30" width="30"
                                         src="{{ child_comment.author.profile.picture.url }}" alt="">
                                </a>
                                <p class="post-text">
                                    <a href="{% url 'social:user-profile' child_comment.author.profile.pk %}">
                                        @{{ child_comment.author }}</a> {{ child_comment.created_at }}
                                </p>
                            </div>

                            {% if request.user == child_comment.author %}
                                <a href="{% url 'social:comment-delete' post.pk child_comment.pk %}"><i
                                        class="fa fa-trash"></i></a>
                            {% endif %}
                            </p>
                            <p>{{ child_comment.comment }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endfor %}

    </div>

{% endblock content %}


templates/social/profile.html
{% extends 'layouts/base.html' %}


{% block content %}
    <div class="container">

        <div class="row mt-5">
            <div class="col-md-3 col-sm-6">
                <a href="{% url 'social:post-list' %}" class="btn btn-light">Back To Feed</a>
            </div>
        </div>

        <div class="row justify-content-center mt-5">
            <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 pt-3">
                <div class="text-center">
                    <img src="{{ profile.picture.url }}" alt="profile" class="rounded-circle" width="100" height="100"/>
                    {% if profile.name %}
                        <h3 class="py-2">{{ profile.name }}
                            <span>
                            {% if request.user == user %}
                                <a href="{% url 'social:update-profile' profile.pk %}" class="text-dark"><i
                                        class="far fa-edit"></i></a>
                            {% endif %}
                        </span>
                        </h3>
                    {% else %}
                        <h3 class="py-4">{{ user.username }}
                            <span>
                            {% if request.user == user %}
                                <a href="{% url 'social:update-profile' profile.pk %}"
                                   class="text-dark"><i
                                        class="far fa-edit"></i></a>
                            {% endif %}
                        </span>
                        </h3>

                    {% endif %}
                </div>

                {% if profile.bio %}
                    <p><span class="font-weight-bold">My Bio:</span> {{ profile.bio }}</p>
                {% endif %}
                <div class="mb-3">
                    <a href="{% url 'social:list-followers' profile.pk %}"
                       class="post-link font-weight-bold text-decoration-none">Followers: {{ number_of_followers }}</a>
                </div>
            </div>
        </div>

        <div class="row justify-content-center mt-5">
            <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 py-3">
                {% if profile.location %}
                    <p><span class="font-weight-bold">Location:</span> {{ profile.location }}</p>
                {% endif %}

                {% if profile.birth_date %}
                    <p><span class="font-weight-bold">Birthday:</span> {{ profile.birth_date }}</p>
                {% endif %}

                {% if user == request.user %}
                {% else %}
                    {% if is_following %}
                        <form method="post" action="{% url 'social:remove-follower' profile.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-danger" type="submit">Unfollow</button>
                        </form>
                    {% else %}
                        <form method="post" action="{% url 'social:add-follower' profile.pk %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-success" type="submit">Follow</button>
                        </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% for post in posts %}
            <div class="row justify-content-center mt-5">
                <div class="col-md-8 col-sm-12 border-bottom">


                    <div class="mt-3">
                        <a href="{% url 'social:user-profile' post.author.profile.pk %}">
                            <img class="rounded-circle post-img float-left mr-2" height="30" width="30"
                                 src="{{ post.author.profile.picture.url }}" alt="">
                        </a>
                        <p class=""><a href="{% url 'social:user-profile' post.author.profile.pk %}"
                                       style="text-decoration: none"
                                       class="text-primary">@{{ post.author }}</a> {{ post.created_at }}
                        </p>
                    </div>


                    <div class="position-relative">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" alt="Post Image" class="post-image">
                        {% endif %}
                        <p>{{ post.body }}</p>
                        <a href="{% url 'social:post-detail' post.pk %}" class="stretched-link"></a>
                    </div>

                    <div class="d-flex flex-row">
                        <form method="post" action="{% url 'social:like' post.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button type="submit"
                                    style="background-color: transparent; border: none; box-shadow: none">
                                <i class="far fa-thumbs-up"> <span>{{ post.like.all.count }}</span> </i>
                            </button>
                        </form>

                        <form method="post" action="{% url 'social:dislike' post.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button type="submit"
                                    style="background-color: transparent; border: none; box-shadow: none">
                                <i class="far fa-thumbs-down"> <span>{{ post.dislike.all.count }}</span> </i>
                            </button>
                        </form>

                    </div>

                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}