Main/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('social/', include('social.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from .views import PostModelListView, PostModelDetailView, \
    PostModelUpdateView, PostModelDeleteView, CommentModelDeleteView, UserProfileModelView, ProfileModelUpdateView, \
    AddFollower, RemoveFollower, PostAddLike, PostAddDislike, UserSearch, ListFollowers, CommentAddLike, \
    CommentAddDislike, CommentReplyView, PostNotification, FollowNotification, RemoveNotification, CreateThread, \
    ListThreads, ThreadView, CreateMessage

app_name = 'social'

urlpatterns = [
    path('', PostModelListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostModelDetailView.as_view(), name='post-detail'),
    path('post/update/<int:pk>/', PostModelUpdateView.as_view(), name='post-update'),
    path('post/delete/<int:pk>/', PostModelDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentModelDeleteView.as_view(), name='comment-delete'),

    path('profile/<int:pk>/', UserProfileModelView.as_view(), name='user-profile'),
    path('profile/update/<int:pk>/', ProfileModelUpdateView.as_view(), name='update-profile'),

    path('profile/<int:pk>/followers/add/', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove/', RemoveFollower.as_view(), name='remove-follower'),

    path('post/<int:pk>/like/', PostAddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike/', PostAddDislike.as_view(), name='dislike'),

    path('post/<int:post>/comment/<int:pk>/like/', CommentAddLike.as_view(), name='comment-like'),
    path('post/<int:post>/comment/<int:pk>/dislike/', CommentAddDislike.as_view(), name='comment-dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/reply/', CommentReplyView.as_view(), name='comment-reply'),

    path('search/', UserSearch.as_view(), name='profile-search'),

    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),

    path('notification/<int:notification_pk>/post/<int:post_pk>/', PostNotification.as_view(),
         name='post-notification'),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>/', FollowNotification.as_view(),
         name='follow-notification'),

    path('notification/delete/<int:notification_pk>/', RemoveNotification.as_view(), name='notification-delete'),

    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),

    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),


]

templates/layouts/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script src="https://kit.fontawesome.com/9fd7e7c824.js" crossorigin="anonymous"></script>

    <title>Twitter Clone</title>
</head>
<body>

{% include 'layouts/header.html' %}


{% block content %}
{% endblock content %}








<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/social.js' %}"></script>


</body>
</html>

templates/layouts/header.html
{% load custom_tags %}

{% block content %}
    <nav class="navbar navbar-light bg-light justify-content-between">
        <a href="{% url 'social:post-list' %}" class="navbar-brand"> <i class="fa fa-comment-o"></i> Social Network</a>
        <form class="form-inline" method="get" action="{% url 'social:profile-search' %}">
            <input name="query" value="{{ request.GET.query }}" class="form-control mr-sm-2" type="search"
                   placeholder="Username" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

            {% if user.is_authenticated %}
                <button class="btn btn-dark ml-2"><a class="text-light" href="{% url 'auth_logout' %}">Logout</a>
                </button>
                <a style="font-size: 25px" class="mr-2 ml-2"
                   href="{% url 'social:user-profile' request.user.profile.pk %}"><i
                        class="fa fa-user-circle"></i></a>

                <div class="nat-item inbox-icon-container">
                    <a href="{% url 'social:inbox' %}" class="inbox-icon">
                        <i class="far fa-paper-plane"></i>
                    </a>
                </div>
                <div style="border-radius: 30%; padding-left: 3px; padding-right: 3px" class="nav-item">


                    {% show_notifications %}
                </div>
            {% else %}
            {% endif %}
        </form>

    </nav>
{% endblock %}