Main/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('', include('landing.urls', namespace='landing')),
    path('social/', include('social.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from .views import PostModelListView, PostModelDetailView, \
    PostModelUpdateView, PostModelDeleteView, CommentModelDeleteView, UserProfileModelView, ProfileModelUpdateView, \
    AddFollower, RemoveFollower, PostAddLike, PostAddDislike, UserSearch, ListFollowers, CommentAddLike, \
    CommentAddDislike, CommentReplyView, PostNotification, FollowNotification, RemoveNotification, CreateThread, \
    ListThreads, ThreadView, CreateMessage

app_name = 'social'

urlpatterns = [
    path('', PostModelListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostModelDetailView.as_view(), name='post-detail'),
    path('post/update/<int:pk>/', PostModelUpdateView.as_view(), name='post-update'),
    path('post/delete/<int:pk>/', PostModelDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentModelDeleteView.as_view(), name='comment-delete'),

    path('profile/<int:pk>/', UserProfileModelView.as_view(), name='user-profile'),
    path('profile/update/<int:pk>/', ProfileModelUpdateView.as_view(), name='update-profile'),

    path('profile/<int:pk>/followers/add/', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove/', RemoveFollower.as_view(), name='remove-follower'),

    path('post/<int:pk>/like/', PostAddLike.as_view(), name='like'),
    path('post/<int:pk>/dislike/', PostAddDislike.as_view(), name='dislike'),

    path('post/<int:post>/comment/<int:pk>/like/', CommentAddLike.as_view(), name='comment-like'),
    path('post/<int:post>/comment/<int:pk>/dislike/', CommentAddDislike.as_view(), name='comment-dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/reply/', CommentReplyView.as_view(), name='comment-reply'),

    path('search/', UserSearch.as_view(), name='profile-search'),

    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),

    path('notification/<int:notification_pk>/post/<int:post_pk>/', PostNotification.as_view(),
         name='post-notification'),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>/', FollowNotification.as_view(),
         name='follow-notification'),

    path('notification/delete/<int:notification_pk>/', RemoveNotification.as_view(), name='notification-delete'),

    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),

    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),


]

templates/show_notifications.html
<div class="dropdown">
    <span class="badge gb-primary notification-badge" style="background-color: #f85555; padding: 6px 8px 6px 8px;"
          onclick="showNotifications()">
        {{ notifications.count }}
    </span>
    <div class="dropdown-content d-none" id="notification-container">

        {% for notification in notifications %}
            {% if notification.post %}
                {% if notification.notification_type == 1 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'social:post-notification' notification.pk notification.post.pk %}">{{ notification.from_user }}
                            liked your post</a>
                        <span class="dropdown-item-close"
                              onclick="removeNotification('{% url 'social:notification-delete' notification.pk %}', '{{ request.path }}')">&times;</span>
                    </div>

                {% elif notification.notification_type == 2 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'social:post-notification' notification.pk notification.post.pk %}">{{ notification.from_user }}
                            commented on your post</a>
                        <span class="dropdown-item-close"
                              onclick="removeNotification('{% url 'social:notification-delete' notification.pk %}', '{{ request.path }}')">&times;</span>
                    </div>
                {% endif %}

            {% elif notification.comment %}
                {% if notification.notification_type == 1 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'social:post-notification' notification.pk notification.comment.post.pk %}">{{ notification.from_user }}
                            liked your comment</a>
                        <span class="dropdown-item-close"
                              onclick="removeNotification('{% url 'social:notification-delete' notification.pk %}', '{{ request.path }}')">&times;</span>
                    </div>

                {% elif notification.notification_type == 2 %}
                    <div class="dropdown-item-parent">
                        <a href="{% url 'social:post-notification' notification.pk notification.comment.post.pk %}">{{ notification.from_user }}
                            replied to your comment</a>
                        <span class="dropdown-item-close"
                              onclick="removeNotification('{% url 'social:notification-delete' notification.pk %}', '{{ request.path }}')">&times;</span>
                    </div>
                {% endif %}

            {% else %}
                <div class="dropdown-item-parent">
                    <a href="{% url 'social:follow-notification' notification.pk notification.from_user.profile.pk %}">{{ notification.from_user }}
                        has started following you</a>
                    <span class="dropdown-item-close"
                          onclick="removeNotification('{% url 'social:notification-delete' notification.pk %}', '{{ request.path }}')">&times;</span>
                </div>
            {% endif %}

        {% endfor %}
    </div>
</div>